(** LayoutExtract.v — extract the aggregate layout model to OCaml (task #46).
 *
 * WHY THIS FILE EXISTS
 *
 * [test/test_layout_conformance.ml] used to open with a module called
 * [RocqMirror]: 150 lines of OCaml described in its own header as "a
 * line-by-line OCaml transcription of the definitions in
 * theories/PtxLayout.v", each function carrying a comment naming the .v
 * definition it copied. The conformance suite then checked the production
 * layout module [Sarek_ir_layout] against that transcription.
 *
 * So the chain from the theory to the thing actually tested had a
 * hand-maintained hop in it. Every theorem in PtxLayout.v — that record leaves
 * never overlap, that every leaf is naturally aligned, that the size is the
 * padded end — was proved about the Rocq definitions and then checked against
 * a copy of them that no tool compared to the original. A typo in the mirror,
 * or an edit to the theory that nobody propagated, produced a green suite
 * proving the OCaml agreed with a transcription that had stopped being the
 * model. The 2026-07-24 audit filed it as "2 unlinked human-maintained hops
 * OCaml <-> mirror <-> proof".
 *
 * The mirror is now generated by the extraction below, so the hop is gone: the
 * suite runs the theory's own definitions, compiled from PtxLayout.v.
 *
 * WHY `Extraction "file.ml"` AND NOT `Extraction Library`
 *
 * Extract.v uses [Extraction Library], which emits one .ml per Rocq module and
 * leaves them referring to their dependencies by name — the files it produces
 * begin `open Datatypes`, `open List`, `open Nat`, modules that exist only if
 * the Stdlib is extracted alongside them. Those files have therefore never
 * compiled; they are committed, regenerated by every proof run, and linked by
 * nothing. (test/test_codegen_ptx_conformance.ml says as much in its header:
 * the extracted modules "require linking", so it hand-mirrors too.)
 *
 * [Extraction "sarek_ptx_layout_model.ml"] instead emits ONE self-contained
 * pair of files with every dependency inlined, which dune can build and a test
 * can link — the difference between a generated artefact and a generated
 * artefact that runs.
 *
 * WHAT IS EXTRACTED
 *
 * The layout API the conformance suite exercises, and nothing else. The
 * theorems are not extracted (proofs have no computational content); they
 * remain the reason to trust the functions below, checked by
 * scripts/check-formal-proofs.sh.
 *
 * REGENERATING
 *
 *   make -f CoqMakefile
 *   python3 ../../scripts/canonicalize-extraction.py \
 *     extraction/sarek_ptx_layout_model.ml extraction/sarek_ptx_layout_model.mli
 *
 * scripts/check-formal-proofs.sh does exactly that from scratch and then
 * byte-compares the result against the committed copies, so a PtxLayout.v edit
 * that is not propagated fails CI rather than sitting in the tree.
 *
 * WHY THE CANONICALISATION STEP EXISTS
 *
 * Rocq's extractor pretty-prints through OCaml's Format module, and Format's
 * line-breaking differs between the OCaml the PROVER itself was built with:
 * 5.5.0 for a local distro install, 4.14.2 inside rocq/rocq-prover:9.1.1. Same
 * Rocq, same sources, same theorems, different wrapping — which made the first
 * CI run of the drift gate fail on a diff whose entire content was where the
 * line broke inside one record literal. Comparing raw output would have fired
 * on every run while being unable to distinguish that from real drift.
 * canonicalize-extraction.py re-flows both sides identically, so the comparison
 * is about the model rather than about which machine ran the extractor.
 *
 * ocamlformat cannot do that job: the extraction runs inside the Rocq image,
 * which ships none, and a job that has ocamlformat has no Rocq.
 *
 * The output is otherwise committed RAW and listed in .ocamlformat-ignore.
 * That is load-bearing: if ocamlformat also rewrote these files the compare
 * would depend on the ocamlformat version too, which is how the five files
 * Extract.v produces ended up restorable but not checkable.
 *)

From CodegenPtx Require Import PtxLayout.

From Stdlib Require Import Extraction.

(* [nat] here indexes record fields, constructor tags and byte offsets of GPU
 * aggregates — quantities bounded by a kernel's source text, nowhere near
 * [max_int]. Mapping to OCaml [int] is what lets the extracted model be
 * compared against [Sarek_ir_layout], which uses [int] offsets. *)
From Stdlib Require Import extraction.ExtrOcamlNatInt.

(* Emit beside this file rather than in the project root, where Extract.v's
 * output lands by default. *)
Set Extraction Output Directory "extraction".

Extraction "sarek_ptx_layout_model.ml"
  align_up scalar_size scalar_align
  falign fsalign fsize fsend
  leaf_size flatten flattens
  record_leaves record_size record_field_offsets record_accepted
  tag_offset tag_size number_args ctor_align payload_struct_size
  variant_payload_offset ctor_layouts max_payload variant_size
  leaf_aligned variant_accepted.
