(******************************************************************************)
(* SPDX-License-Identifier: CECILL-B                                          *)
(* SPDX-FileCopyrightText: 2026 Mathias Bourgoin <mathias.bourgoin@gmail.com> *)
(******************************************************************************)

(******************************************************************************
 * Sarek_type_helpers - Type-safe interpreter helper registry
 *
 * Generated by [@@sarek.type] PPX for custom type conversion.
 * Each [@@sarek.type] record type gets a helper module registered here.
 ******************************************************************************)

open Sarek_value

(** Module signature for type-specific helpers *)
module type HELPERS = sig
  type t

  val type_id : t Sarek_ir_types.Type_id.t

  val from_values : value array -> t

  val to_values : t -> value array

  val get_field : t -> string -> value

  (** Immediate field names, in declaration order — the SAME order {!to_values}
      produces and {!from_values} consumes, so a name's position in this list IS
      its index in the [value array] of the [VRecord].

      That correspondence is what makes an in-place field STORE possible:
      [get_field] can only read, and going through [to_values]/[from_value]
      round-trips via the OCaml record and therefore COPIES, which is how the
      interpreter came to refuse [v.(i).f <- e] outright (backlog-172).

      For a PPX-generated helper the correspondence holds by construction: the
      list comes from the same [labels] list that generates [to_values] and
      [get_field], so those three cannot drift. For a HAND-WRITTEN
      implementation it is an obligation the author carries, not a guarantee —
      the one in-tree hand-written implementor
      (sarek/sarek/test/test_sarek_type_helpers.ml) maintains it manually, and
      its own test checks [field_index] against [to_values]' output rather than
      against hardcoded slots so that a drift there fails.

      Empty for a variant, which has no named fields.

      {b Breaking for out-of-tree implementors.} This is a new REQUIRED [val] in
      a public module type, so any [HELPERS] implementation outside this
      repository stops compiling until it adds the list. There is no
      non-breaking spelling: a module type cannot carry a default, and the index
      cannot be derived from the rest of the signature — [to_values] needs a
      value of type [t] and [lookup] has none. Adding the obligation is the
      price of being able to WRITE a field at all; every in-tree implementor is
      PPX-generated except the test mock above. *)
  val field_names : string list

  (** Convert to VRecord representation *)
  val to_value : t -> value

  (** Convert from VRecord representation *)
  val from_value : value -> t
end

(** First-class module wrapper for helpers - fully type-safe! *)
type any_helpers =
  | AnyHelpers : (module HELPERS with type t = 'a) -> any_helpers

(** Global registry mapping type names to their helper modules *)
let registry : (string, any_helpers) Hashtbl.t = Hashtbl.create 32

(** Register a helper module for a type. Called by generated code at module
    init. *)
let register (type_name : string) (helpers : any_helpers) : unit =
  Hashtbl.replace registry type_name helpers

(** Helper functions for custom type conversion *)
type helpers = {
  from_values : value array -> value;  (** Construct VRecord from field array *)
  to_values : value -> value array;  (** Deconstruct VRecord to field array *)
  get_field : value -> string -> value;  (** Field access from VRecord *)
  field_index : string -> int option;
      (** Position of a field in the [VRecord]'s [value array], or [None] if the
          type has no such field. Derived from [HELPERS.field_names], whose
          order is [to_values]' order. This is the only handle a caller has for
          writing a field: see the [LRecordField] arm of
          [Sarek_ir_interp_eval.assign_lvalue]. *)
}

(** Look up helpers for a type. Returns None if not registered. *)
let lookup (type_name : string) : helpers option =
  match Hashtbl.find_opt registry type_name with
  | None -> None
  | Some (AnyHelpers h) ->
      (* Unpack the existential first-class module *)
      let (module H) = h in
      Some
        {
          from_values = (fun arr -> H.to_value (H.from_values arr));
          to_values = (fun v -> H.to_values (H.from_value v));
          get_field = (fun v field -> H.get_field (H.from_value v) field);
          field_index =
            (fun field ->
              let rec find i = function
                | [] -> None
                | f :: _ when String.equal f field -> Some i
                | _ :: rest -> find (i + 1) rest
              in
              find 0 H.field_names);
        }

let lookup_typed (type a) (type_id : a Sarek_ir_types.Type_id.t) :
    (module HELPERS with type t = a) option =
  let found =
    Hashtbl.fold
      (fun _ helpers acc ->
        match acc with
        | Some _ -> acc
        | None -> (
            match helpers with
            | AnyHelpers h -> (
                let (module H) = h in
                match Sarek_ir_types.Type_id.equal type_id H.type_id with
                | Some Sarek_ir_types.Type_id.Refl ->
                    Some (module H : HELPERS with type t = a)
                | None -> None)))
      registry
      None
  in
  found

(** Check if a type has registered helpers *)
let has_helpers (type_name : string) : bool = Hashtbl.mem registry type_name
