(******************************************************************************)
(* SPDX-License-Identifier: CECILL-B                                          *)
(* SPDX-FileCopyrightText: 2026 Mathias Bourgoin <mathias.bourgoin@gmail.com> *)
(******************************************************************************)

(** End-to-end test for the PTX external kernel path.

    Validates that a PTX string produced by tracing
    Sarek_ir_ptx.demo_vector_add_ptx can be loaded via
    Cuda_api.Kernel.load_from_ptx and executed on real hardware, producing
    correct float32 addition results.

    This test skips cleanly when no CUDA device is present. *)

open Sarek_cuda

(* The PTX generated by demo_vector_add_ptx () — register allocation traced
   from the emitter and validated by ptxas --gpu-name sm_86 (2026-06-13). *)
let vector_add_ptx =
  {|.version 8.0
.target sm_86
.address_size 64

.entry vector_add(
    .param .u64 param_a,
    .param .u64 param_b,
    .param .u64 param_c,
    .param .u32 param_n
)
{
    .reg .u32 %r<7>;
    .reg .u64 %rd<12>;
    .reg .f32 %f<3>;
    .reg .pred %p<2>;

    ld.param.u64 %rd0, [param_a];
    ld.param.u64 %rd1, [param_b];
    ld.param.u64 %rd2, [param_c];
    ld.param.u32 %r0, [param_n];
    mov.u32 %r1, %tid.x;
    mov.u32 %r2, %ctaid.x;
    mov.u32 %r3, %ntid.x;
    mul.lo.u32 %r4, %r2, %r3;
    add.u32 %r5, %r1, %r4;
    setp.lt.s32 %p0, %r5, %r0;
    selp.u32 %r6, 1, 0, %p0;
    setp.ne.u32 %p1, %r6, 0;
    @!%p1 bra L0;
    cvt.u64.u32 %rd3, %r5;
    shl.b64 %rd4, %rd3, 2;
    add.u64 %rd5, %rd0, %rd4;
    ld.global.f32 %f0, [%rd5];
    cvt.u64.u32 %rd6, %r5;
    shl.b64 %rd7, %rd6, 2;
    add.u64 %rd8, %rd1, %rd7;
    ld.global.f32 %f1, [%rd8];
    add.f32 %f2, %f0, %f1;
    cvt.u64.u32 %rd9, %r5;
    shl.b64 %rd10, %rd9, 2;
    add.u64 %rd11, %rd2, %rd10;
    st.global.f32 [%rd11], %f2;
L0:
    ret;
}
|}

let n = 1024

let block_size = 256

let make_host_array size f =
  let ba = Bigarray.Array1.create Bigarray.float32 Bigarray.c_layout size in
  for i = 0 to size - 1 do
    ba.{i} <- f i
  done ;
  ba

let test_vector_add () =
  if not (Cuda_api.is_available ()) then (
    Printf.printf "  [SKIP] no CUDA device\n%!" ;
    (* Alcotest skip not available without raising; just pass *)
    ())
  else begin
    Cuda_api.Device.init () ;
    let dev = Cuda_api.Device.get 0 in

    (* Host arrays: a[i] = float(i), b[i] = float(n - i) *)
    let h_a = make_host_array n (fun i -> float_of_int i) in
    let h_b = make_host_array n (fun i -> float_of_int (n - i)) in
    let h_c = make_host_array n (fun _ -> 0.0) in

    (* Device buffers *)
    let d_a = Cuda_api.Memory.alloc dev n Bigarray.float32 in
    let d_b = Cuda_api.Memory.alloc dev n Bigarray.float32 in
    let d_c = Cuda_api.Memory.alloc dev n Bigarray.float32 in

    Cuda_api.Memory.host_to_device ~src:h_a ~dst:d_a ;
    Cuda_api.Memory.host_to_device ~src:h_b ~dst:d_b ;

    (* Load PTX and launch *)
    let kernel =
      Cuda_api.Kernel.load_from_ptx dev ~name:"vector_add" ~ptx:vector_add_ptx
    in
    let grid = ((n + block_size - 1) / block_size, 1, 1) in
    let block = (block_size, 1, 1) in
    Cuda_api.Kernel.launch
      kernel
      ~args:
        [
          Cuda_api.Kernel.ArgBuffer d_a;
          Cuda_api.Kernel.ArgBuffer d_b;
          Cuda_api.Kernel.ArgBuffer d_c;
          Cuda_api.Kernel.ArgInt32 (Int32.of_int n);
        ]
      ~grid
      ~block
      ~shared_mem:0
      ~stream:None ;

    (* Synchronise and read back *)
    Cuda_api.Device.synchronize dev ;
    Cuda_api.Memory.device_to_host ~src:d_c ~dst:h_c ;

    (* Verify: a[i] + b[i] = i + (n - i) = n for all i *)
    let expected = float_of_int n in
    let ok = ref true in
    for i = 0 to n - 1 do
      let got = h_c.{i} in
      if abs_float (got -. expected) > 1e-4 then begin
        Printf.printf "  FAIL at i=%d: expected %f got %f\n%!" i expected got ;
        ok := false
      end
    done ;
    Alcotest.(check bool) "vector_add results correct" true !ok ;

    (* Clean up *)
    Cuda_api.Memory.free d_a ;
    Cuda_api.Memory.free d_b ;
    Cuda_api.Memory.free d_c
  end

let test_generate_vector_add () =
  let generated = Sarek_ir_ptx.demo_vector_add_ptx () in
  Alcotest.(check string)
    "demo_vector_add_ptx output matches hardcoded PTX"
    vector_add_ptx
    generated

let () =
  Alcotest.run
    "ptx_external"
    [
      ( "emitter",
        [
          Alcotest.test_case
            "demo_vector_add_ptx matches hardcoded PTX"
            `Quick
            test_generate_vector_add;
        ] );
      ( "vector_add",
        [Alcotest.test_case "ptx load + launch + verify" `Quick test_vector_add]
      );
    ]
